### ISSUE TITLE
Login Fehler

### ISSUE THREAD

**Issue by sigi2345** [TA2k/ioBroker.psa#1]
Hallo, 

1. Test

`
psa.0 | 2021-06-22 23:26:45.799 | warn | State "psa.0.info.connection" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
psa.0 | 2021-06-22 23:26:45.794 | error | Login failed
psa.0 | 2021-06-22 23:26:45.794 | error | {"error":"invalid_grant","error_description":"The provided access grant is invalid, expired, or revoked."}
psa.0 | 2021-06-22 23:26:45.794 | error | Login failed
psa.0 | 2021-06-22 23:26:45.794 | error | Error: Request failed with status code 400
psa.0 | 2021-06-22 23:26:45.386 | info | starting. Version 0.0.1 in C:/Program Files/iobroker/Home/node_modules/iobroker.psa, node: v12.22.1, js-controller: 3.3.14
psa.0 | 2021-06-22 23:26:45.386 | info | starting. Version 0.0.1 in C:/Program Files/iobroker/Home/node_modules/iobroker.psa, node: v12.22.1, js-controller: 3.3.14
psa.0 | 2021-06-22 23:26:41.463 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
psa.0 | 2021-06-22 23:26:41.462 | info | terminating
psa.0 | 2021-06-22 23:26:41.462 | warn | Clear yet terminated interval undefined
psa.0 | 2021-06-22 23:26:41.461 | warn | Clear yet terminated interval undefined
psa.0 | 2021-06-22 23:26:41.461 | info | Got terminate signal TERMINATE_YOURSELF

`Plattform: Windows
RAM: 16 GB 
Node.js: 12.22.1
NPM: 6.14.12
JS Controller: 3.3.14
Admin: 5.1.9
Web: 3.4.1
Socket.io: 3.1.4
Script Engine: 5.1.3
IOT: 1.8.22
VIS: 1.3.10
HM-Rega: 3.0.24
HM-RPC: 1.14.41
Jarvis: 2.2.0
Backitup: 2.1.12
Cloud: 4.0.11
ICal: 1.9.3
iQontrol: 1.8.0
fb-checkpresence: 1.1.5
Hue: 3.5.18
`

PKW:  Peugeot 2008 BJ 2014

**Comment by TA2k** [comment]
Die myPeugot App funktioniert bei dir?

**Comment by sigi2345** [comment]
> Die myPeugot App funktioniert bei dir?

Ja, einwandfrei.
