### ISSUE TITLE
API Fehler Opel

### ISSUE THREAD

**Issue by thstickel** [TA2k/ioBroker.psa#10]
**API Fehler Opel**  

Hallo, nach der Installation und der Eingabe der Credentials wird der Adapter grün und er werden alle Datenpunkte angelegt. Auch der Wagen mit der FIN wird gefunden und in einem Subfolder angelegt. Allerdings werden alle darunter liegenden Datenpunkte nur mit der URL des API-Requests gefüllt.

Der Wagen ist ein Opel Corsa Elektro (Bj 2022)

Hier der Log (noch nicht im Debug-Modus)

![300241013_2225327010966611_2225110561893387925_n](https://user-images.githubusercontent.com/25841553/186097583-4f5c6c5c-ce88-4057-a33b-af07cf71017a.jpeg)

**Versions:**  
 - Adapter version: v0.0.10
 - JS-Controller version: 4.0.23
 - Node version: v16.16.0
 - Operating system: Debian Buster

**Comment by TA2k** [comment]
schick mal den debug log an mich tombox2020@gmail.com

**Comment by thstickel** [comment]
Hallo, ist der Debug-Log bei Dir angekommen?

**Comment by thstickel** [comment]
Das Problem ist jetzt behoben. Ich könnte mir vorstellen, dass die Kalibrierfahrt von mindestens 20 Minuten noch fehlte. Außerdem habe ich noch eine Update der Software durchgeführt. jetzt werden alle Objekte von Adapter mit Inhalt gefüllt. Vielen Dank für Deinen Support!
