### ISSUE TITLE
401 Authentication error since some days 

### ISSUE THREAD

**Issue by marcsauter75** [TA2k/ioBroker.psa#13]
**Describe the bug**  

Since some days i got the error:

psa.0 | 2022-09-20 08:41:35.480 | warn | {"errors":{"401":"UNAUTHORIZED"}}
-- | -- | -- | --
psa.0 | 2022-09-20 08:41:35.478 | warn | AxiosError: Request failed with status code 401

But I can login normally into the Peugeot APP so no issue with the passowrd. 
I checked the password multiple times

also updated to .11 version beta but doesn´t help.

Does anybody else have this problem ?

**Comment by marcsauter75** [comment]
I got back to version .10 now ... 
same issue .. but login seems successfull



psa.0 | 2022-09-20 09:13:12.972 | warn | OldAPI Login failed, only relevant for non eletric cars
-- | -- | -- | --
psa.0 | 2022-09-20 09:13:12.972 | warn | "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body>\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n</html>\r\n"
psa.0 | 2022-09-20 09:13:12.971 | warn | receive old api failed
psa.0 | 2022-09-20 09:13:12.969 | warn | Error: Request failed with status code 403
psa.0 | 2022-09-20 09:13:12.502 | info | Login successful

**Comment by marcsauter75** [comment]
can i ignore that error - cause of only for "non electric cars" ?

**Comment by TA2k** [comment]
Its only a warning you can ignore it

**Comment by marcsauter75** [comment]
Can I disable that warning ?
